# Generated by Django 3.2.16 on 2024-04-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookCode', models.CharField(max_length=200)),
                ('customerCode', models.CharField(max_length=200)),
            ],
        ),
    ]
